"""add deleted_at to transactions

Revision ID: 0f38779589e6
Revises: 86b52bdcb313
Create Date: 2026-09-14 14:15:32.894979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f38779589e6'
down_revision: Union[str, None] = '86b52bdcb313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deleted_at')
    # ### end Alembic commands ###
